export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const SIGN_OUT = "SIGN_OUT";

export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";

export const SELECT_MAIN_TYPE = "SELECT_MAIN_TYPE";
export const SELECT_MAIN_FEEDS_TYPE = "SELECT_MAIN_FEEDS_TYPE";

export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const TOGGLE_CATEGORY_STATUS = "TOGGLE_CATEGORY_STATUS";
export const TOGGLE_SOURCE_STATUS = "TOGGLE_SOURCE_STATUS";
export const CHANGE_CATEGORY_ORDER = "CHANGE_CATEGORY_ORDER";

export const GET_ARTICLES = "GET_ARTICLES";
export const GET_NEWS_ARTICLE = "GET_NEWS_ARTICLE";
export const GET_REDDIT_POST = "GET_REDDIT_POST";

export const SELECT_ARTICLE = "SELECT_ARTICLE";
export const REFRESH_ARTICLE = "REFRESH_ARTICLE";
export const NEED_GET_ARTICLES = "NEED_GET_ARTICLES";

export const SELECT_NEWS_COUNTRY = "SELECT_NEWS_COUNTRY";
export const SELECT_NEWS_TYPE = "SELECT_NEWS_TYPE";

export const DATA_REQUEST_PENDING = "DATA_REQUEST_PENDING";
export const DATA_REQUEST_SUCCESS = "DATA_REQUEST_SUCCESS";
export const DATA_REQUEST_FAIL = "DATA_REQUEST_FAIL";

export const INIT_SCROLL_POS = "INIT_SCROLL_POS";
export const SAVE_SCROLL_POS = "SAVE_SCROLL_POS";

export const GET_NEWS_FIRSTPAGE = "GET_NEWS_FIRSTPAGE";
export const GET_NEWS_NEXTPAGE = "GET_NEWS_NEXTPAGE"
export const GET_REDDIT_FIRSTPAGE = "GET_REDDIT_FIRSTPAGE";
export const GET_REDDIT_NEXTPAGE = "GET_REDDIT_NEXTPAGE";

export const UPDATE_SEARCH_KEY = "UPDATE_SEARCH_KEY";
export const UPDATE_SEARCH_RESULT = "UPDATE_SEARCH_RESULT";
export const SELECT_SEARCH_ARTICLE = "SELECT_SEARCH_ARTICLE";
export const INIT_SEARCH_SCROLL_POS = "INIT_SEARCH_SCROLL_POS";
export const SAVE_SEARCH_SCROLL_POS = "SAVE_SEARCH_SCROLL_POS";

export const SHOW_TOP_NAVBAR = "SHOW_TOP_NAVBAR";
export const SHOW_BOTTOM_NAVBAR = "SHOW_BOTTOM_NAVBAR";

export const LOADING_START = "LOADING_START";
export const LOADING_END = "LOADING_END";
export const LOADING_FAIL = "LOADING_FAIL";
