export const ALL    = 0     // All Countries
export const ARG    = 32    // Argentina
export const AUS    = 36    // Australia
export const BGD    = 50    // Bangladesh
export const BRA    = 76    // Brazil
export const CAN    = 124   // Canada
export const CHN    = 156   // China
export const CZE    = 203   // Czech Republic
export const EGY    = 818   // Egypt
export const ETH    = 231   // Ethiopia
export const FRA    = 250   // France
export const DEU    = 276   // Germany
export const GHA    = 288   // Ghana
export const HKG    = 344   // Hong Kong
export const HUN    = 348   // Hungary
export const IND    = 356   // India
export const IDN    = 360   // Indonesia
export const IRN    = 364   // Iran
export const ISR    = 376   // Israel
export const JPN    = 392   // Japan
export const KEN    = 404   // Kenya
export const PRK    = 408   // Korea, Democratic People's Republic of
export const KOR    = 410   // Korea, Republic of
export const MYS    = 458   // Malaysia
export const MEX    = 484   // Mexico
export const NGA    = 566   // Nigeria
export const PAK    = 586   // Pakistan
export const PHL    = 608   // Philippines
export const POL    = 616   // Poland
export const RUS    = 643   // Russian Federation
export const SAU    = 682   // Saudi Arabia
export const SGP    = 702   // Singapore
export const ZAF    = 710   // South Africa
export const ESP    = 724   // Spain
export const LKA    = 144   // Sri Lanka
export const SWE    = 752   // Sweden
export const TWN    = 158   // Taiwan
export const THA    = 764   // Thailand
export const TUR    = 792   // Turkey
export const ARE    = 784   // United Arab Emirates
export const GBR    = 826   // United Kingdom
export const USA    = 840   // United States