import * as category from '../constants/category';
import * as source from '../constants/source';
import * as type from '../constants/newstype';
import * as state from '../constants/state';


export const conf_sources = [
    {
        value: source.AN_NYTIMES_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.ANGLOSPHERE,
        state: state.USA,
        label: 'New York Times',
        cimage: '/static/images/flags/usa.png',
        image: '/static/images/news/nytimes.jpg',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.AN_WSJ_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.ANGLOSPHERE,
        state: state.USA,
        label: 'Wall Street Journal',
        cimage: '/static/images/flags/usa.png',
        image: '/static/images/news/wsj.jpg',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.AN_THEGLOBEANDMAIL_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.ANGLOSPHERE,
        state: state.CAN,
        label: 'The Globe and Mail',
        cimage: '/static/images/flags/canada.png',
        image: '/static/images/news/theglobeandmail.jpg',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.AN_USATODAY_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.ANGLOSPHERE,
        state: state.USA,
        label: 'USA Today',
        cimage: '/static/images/flags/usa.png',
        image: '/static/images/news/usatoday.gif',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.AN_LAPRESSE_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.ANGLOSPHERE,
        state: state.CAN,
        label: 'La Presse',
        cimage: '/static/images/flags/canada.png',
        image: '/static/images/news/lapresseca.png',
        translation: { lang: 'French', engine: 'AWS' },
        selected: true,
        cached: false
    },
    {
        value: source.AN_THEAGE_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.ANGLOSPHERE,
        state: state.AUS,
        label: 'The Age',
        cimage: '/static/images/flags/australia.png',
        image: '/static/images/news/theage.png',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.AN_ECONOMIST_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.ANGLOSPHERE,
        state: state.GBR,
        label: 'Economist',
        cimage: '/static/images/flags/uk.png',
        image: '/static/images/news/economist.jpg',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.AN_BBC_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.ANGLOSPHERE,
        state: state.GBR,
        label: 'BBC',
        cimage: '/static/images/flags/uk.png',
        image: '/static/images/news/bbc.jpg',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.AN_CBC_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.ANGLOSPHERE,
        state: state.CAN,
        label: 'CBC',
        cimage: '/static/images/flags/canada.png',
        image: '/static/images/news/cbc.jpg',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.AN_NYTIMES_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.ANGLOSPHERE,
        state: state.USA,
        label: 'New York Times',
        cimage: '/static/images/flags/usa.png',
        image: '/static/images/news/nytimes.jpg',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.AN_USATODAY_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.ANGLOSPHERE,
        state: state.USA,
        label: 'USA Today',
        cimage: '/static/images/flags/usa.png',
        image: '/static/images/news/usatoday.gif',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.AN_WSJ_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.ANGLOSPHERE,
        state: state.USA,
        label: 'Wall Street Journal',
        cimage: '/static/images/flags/usa.png',
        image: '/static/images/news/wsj.jpg',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.AN_BBC_AUSTRALIA_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.ANGLOSPHERE,
        state: state.GBR,
        label: 'BBC Australia',
        cimage: '/static/images/flags/uk.png',
        image: '/static/images/news/bbc.jpg',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.GC_PEOPLESDAILY_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.GREATERCHINA,
        state: state.CHN,
        label: "People's Daily",
        cimage: '/static/images/flags/china.png',
        image: '/static/images/news/peoplesdaily.jpg',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.GC_GLOBALTIMES_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.GREATERCHINA,
        state: state.CHN,
        label: 'Global Times',
        cimage: '/static/images/flags/china.png',
        image: '/static/images/news/globaltimes.jpg',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.GC_SCMP_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.GREATERCHINA,
        state: state.HKG,
        label: 'SCMP',
        cimage: '/static/images/flags/hongkong.png',
        image: '/static/images/news/scmp.jpg',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.GC_BUSINESSTIMES_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.GREATERCHINA,
        state: state.SGP,
        label: 'Business Times',
        cimage: '/static/images/flags/singapore.png',
        image: '/static/images/news/businesstimes.png',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.GC_TAIWANDAILY_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.GREATERCHINA,
        state: state.TWN,
        label: 'Taiwan Daily',
        cimage: '/static/images/flags/taiwan.png',
        image: '/static/images/news/taiwannews.png',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.GC_SOUTHERNWEEK_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.GREATERCHINA,
        state: state.CHN,
        label: 'Southern Weekend',
        cimage: '/static/images/flags/china.png',
        image: '/static/images/news/infzm.png',
        translation: { lang: 'Chinese', engine: 'Azure' },
        selected: true,
        cached: false
    },
    {
        value: source.GC_SCMP_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.GREATERCHINA,
        state: state.HKG,
        label: 'SCMP',
        cimage: '/static/images/flags/hongkong.png',
        image: '/static/images/news/scmp.jpg',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.GC_STRAITSTIMES_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.GREATERCHINA,
        state: state.SGP,
        label: 'Straits Times',
        cimage: '/static/images/flags/singapore.png',
        image: '/static/images/news/straitstimes.jpg',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.GC_TAIWANDAILY_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.GREATERCHINA,
        state: state.TWN,
        label: 'Taiwan Daily',
        cimage: '/static/images/flags/taiwan.png',
        image: '/static/images/news/taiwannews.png',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.GC_BBC_CHINA_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.GREATERCHINA,
        state: state.GBR,
        label: 'BBC China',
        cimage: '/static/images/flags/uk.png',
        image: '/static/images/news/bbc.jpg',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.WE_LEMONDE_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.WESTEUROPE,
        state: state.FRA,
        label: "Le Monde",
        cimage: '/static/images/flags/france.png',
        image: '/static/images/news/lemonde.jpg',
        translation: { lang: 'French', engine: 'AWS' },
        selected: true,
        cached: false
    },
    {
        value: source.WE_ELPAIS_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.WESTEUROPE,
        state: state.ESP,
        label: 'El Pais',
        cimage: '/static/images/flags/spain.png',
        image: '/static/images/news/elpais.jpg',
        translation: { lang: 'Spanish', engine: 'Google' },
        selected: true,
        cached: false
    },
    {
        value: source.WE_FRANKFURTER_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.WESTEUROPE,
        state: state.DEU,
        label: 'Frankfurter Allgemaine',
        cimage: '/static/images/flags/germany.png',
        image: '/static/images/news/frankfurter.jpg',
        translation: { lang: 'German', engine: 'AWS' },
        selected: true,
        cached: false
    },
    {
        value: source.WE_SUDDEUTSCH_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.WESTEUROPE,
        state: state.DEU,
        label: 'Suddeutsch Zeitung',
        cimage: '/static/images/flags/germany.png',
        image: '/static/images/news/suddeutsch.jpg',
        translation: { lang: 'German', engine: 'AWS' },
        selected: true,
        cached: false
    },
    {
        value: source.WE_DAGENSNYHETER_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.WESTEUROPE,
        state: state.SWE,
        label: 'Dagens Nyheter',
        cimage: '/static/images/flags/sweden.png',
        image: '/static/images/news/dagensnyheter.jpg',
        translation: { lang: 'Swedish', engine: 'Azure' },
        selected: true,
        cached: false
    },
    {
        value: source.WE_LEFIGARO_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.WESTEUROPE,
        state: state.FRA,
        label: "Le Figaro",
        cimage: '/static/images/flags/france.png',
        image: '/static/images/news/lefigaro.png',
        translation: { lang: 'French', engine: 'AWS' },
        selected: true,
        cached: false
    },
    {
        value: source.WE_ELPAIS_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.WESTEUROPE,
        state: state.ESP,
        label: 'El Pais',
        cimage: '/static/images/flags/spain.png',
        image: '/static/images/news/elpais.jpg',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.WE_DIEWELT_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.WESTEUROPE,
        state: state.DEU,
        label: 'Die Welt',
        cimage: '/static/images/flags/germany.png',
        image: '/static/images/news/diewelt.png',
        translation: { lang: 'German', engine: 'AWS' },
        selected: true,
        cached: false
    },
    {
        value: source.EE_WYBORCZA_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.EASTEUROPE,
        state: state.POL,
        label: "Gazeta Wyborcza",
        cimage: '/static/images/flags/poland.png',
        image: '/static/images/news/wyborcza.jpg',
        translation: { lang: 'Polish', engine: 'Azure' },
        selected: true, 
        cached: false
    },
    {
        value: source.EE_MAGYARHIRLAP_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.EASTEUROPE,
        state: state.HUN,
        label: "Magyar Hirlap",
        cimage: '/static/images/flags/hungary.png',
        image: '/static/images/news/magyarhirlap.png',
        translation: { lang: 'Hungarian', engine: 'Azure' },
        selected: true,
        cached: false
    },
    {
        value: source.EE_INFO_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.EASTEUROPE,
        state: state.CZE,
        label: "Info",
        cimage: '/static/images/flags/czech.png',
        image: '/static/images/news/infocz.jpg',
        translation: { lang: 'Czech', engine: 'Azure' },
        selected: true,
        cached: false
    },
    {
        value: source.EE_WYBORCZA_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.EASTEUROPE,
        state: state.POL,
        label: "Gazeta Wyborcza",
        cimage: '/static/images/flags/poland.png',
        image: '/static/images/news/wyborcza.jpg',
        translation: { lang: 'Polish', engine: 'Azure' },
        selected: true,
        cached: false
    },
    {
        value: source.EE_MAGYARHIRLAP_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.EASTEUROPE,
        state: state.HUN,
        label: "Magyar Hirlap",
        cimage: '/static/images/flags/hungary.png',
        image: '/static/images/news/magyarhirlap.png',
        translation: { lang: 'Hungarian', engine: 'Azure' },
        selected: true,
        cached: false
    },
    {
        value: source.EE_LIDOVKY_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.EASTEUROPE,
        state: state.CZE,
        label: "Lidovky",
        cimage: '/static/images/flags/czech.png',
        image: '/static/images/news/lidovky.png',
        translation: { lang: 'Czech', engine: 'Azure' },
        selected: true,
        cached: false
    },
    {
        value: source.RU_IZVESTIA_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.RUSSIA,
        state: state.RUS,
        label: 'Izvestia',
        cimage: '/static/images/flags/russia.png',
        image: '/static/images/news/izvestia.jpg',
        translation: { lang: 'Russian', engine: 'Azure' },
        selected: true,
        cached: false
    },
    {
        value: source.RU_NOVAYAGAZETA_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.RUSSIA,
        state: state.RUS,
        label: 'Novayagazeta',
        cimage: '/static/images/flags/russia.png',
        image: '/static/images/news/novayagazeta.jpg',
        translation: { lang: 'Russian', engine: 'AWS' },
        selected: true,
        cached: false
    },
    {
        value: source.RU_GAZETA_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.RUSSIA,
        state: state.RUS,
        label: 'Gazeta',
        cimage: '/static/images/flags/russia.png',
        image: '/static/images/news/gazeta.jpg',
        translation: { lang: 'Russian', engine: 'AWS' },
        selected: true,
        cached: false
    },
    {
        value: source.RU_IZVESTIA_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.RUSSIA,
        state: state.RUS,
        label: 'Izvestia',
        cimage: '/static/images/flags/russia.png',
        image: '/static/images/news/izvestia.jpg',
        translation: { lang: 'Russian', engine: 'Azure' },
        selected: true,
        cached: false
    },
    {
        value: source.RU_NOVAYAGAZETA_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.RUSSIA,
        state: state.RUS,
        label: 'Novayagazeta',
        cimage: '/static/images/flags/russia.png',
        image: '/static/images/news/novayagazeta.jpg',
        translation: { lang: 'Russian', engine: 'AWS' },
        selected: true,
        cached: false
    },
    {
        value: source.RU_GAZETA_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.RUSSIA,
        state: state.RUS,
        label: 'Gazeta',
        cimage: '/static/images/flags/russia.png',
        image: '/static/images/news/gazeta.jpg',
        translation: { lang: 'Russian', engine: 'AWS' },
        selected: true,
        cached: false
    },
    {
        value: source.LA_JORNADA_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.LATINAMERICA,
        state: state.MEX,
        label: 'Jornada',
        cimage: '/static/images/flags/mexico.png',
        image: '/static/images/news/jornada.jpg',
        translation: { lang: 'Spanish', engine: 'Google' },
        selected: true,
        cached: false
    },
    {
        value: source.LA_LANACION_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.LATINAMERICA,
        state: state.ARG,
        label: 'La Nacion',
        cimage: '/static/images/flags/argentina.png',
        image: '/static/images/news/lanacion.jpg',
        translation: { lang: 'Spanish', engine: 'Google' },
        selected: true,
        cached: false
    },
    {
        value: source.LA_OGLOBO_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.LATINAMERICA,
        state: state.BRA,
        label: 'O Globo',
        cimage: '/static/images/flags/brazil.png',
        image: '/static/images/news/oglobo.png',
        translation: { lang: 'Portuguese', engine: 'Azure' },
        selected: true,
        cached: false
    },
    {
        value: source.LA_GAZETADEPOVO_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.LATINAMERICA,
        state: state.BRA,
        label: 'Gazeta de Povo',
        cimage: '/static/images/flags/brazil.png',
        image: '/static/images/news/gazetadepovo.gif',
        translation: { lang: 'Portuguese', engine: 'Azure' },
        selected: true,
        cached: false
    },
    {
        value: source.LA_ELUNIVERSAL_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.LATINAMERICA,
        state: state.MEX,
        label: 'El Universal',
        cimage: '/static/images/flags/mexico.png',
        image: '/static/images/news/eluniversal.png',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.LA_CLARIN_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.LATINAMERICA,
        state: state.ARG,
        label: 'Clarin',
        cimage: '/static/images/flags/argentina.png',
        image: '/static/images/news/clarin.png',
        translation: { lang: 'Spanish', engine: 'Google' },
        selected: true,
        cached: false
    },
    {
        value: source.LA_FOLHA_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.LATINAMERICA,
        state: state.BRA,
        label: 'Folha de Sao Paulo',
        cimage: '/static/images/flags/brazil.png',
        image: '/static/images/news/folha.png',
        translation: { lang: 'Portuguese', engine: 'Azure' },
        selected: true,
        cached: false
    },
    {
        value: source.MEA_IRANDAILY_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.MIDDLEEAST,
        state: state.IRN,
        label: 'Iran Daily',
        cimage: '/static/images/flags/iran.png',
        image: '/static/images/news/irandaily.gif',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.MEA_YNET_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.MIDDLEEAST,
        state: state.ISR,
        label: 'Ynet',
        cimage: '/static/images/flags/israel.png',
        image: '/static/images/news/yedioth.png',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.MEA_HAARETZ_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.MIDDLEEAST,
        state: state.ISR,
        label: 'Haaretz',
        cimage: '/static/images/flags/israel.png',
        image: '/static/images/news/haaretz.gif',
        translation: { lang: 'Hebrew', engine: 'AWS' },
        selected: true,
        cached: false
    },
    {
        value: source.MEA_ALAWSAT_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.MIDDLEEAST,
        state: state.SAU,
        label: 'Asharq al Awsat',
        cimage: '/static/images/flags/saudiarabia.png',
        image: '/static/images/news/alawsat.jpg',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.MEA_ALWAFD_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.MIDDLEEAST,
        state: state.EGY,
        label: 'Al Wafd',
        cimage: '/static/images/flags/egypt.png',
        image: '/static/images/news/alwafd.png',
        translation: { lang: 'Arabic', engine: 'Azure' },
        selected: true,
        cached: false
    },
    {
        value: source.MEA_KHALEEJTIMES_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.MIDDLEEAST,
        state: state.ARE,
        label: 'Khaleej Times',
        cimage: '/static/images/flags/uae.png',
        image: '/static/images/news/khaleejtimes.jpg',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.MEA_DAILYSABAH_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.MIDDLEEAST,
        state: state.TUR,
        label: 'Daily Sabah',
        cimage: '/static/images/flags/turkey.png',
        image: '/static/images/news/dailysabah.jpg',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.MEA_BBC_PERSIAN_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.MIDDLEEAST,
        state: state.GBR,
        label: 'BBC Persian',
        cimage: '/static/images/flags/uk.png',
        image: '/static/images/news/bbc.jpg',
        translation: { lang: 'Persian', engine: 'Google' },
        selected: true,
        cached: false
    },
    {
        value: source.MEA_YNET_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.MIDDLEEAST,
        state: state.ISR,
        label: 'Ynet',
        cimage: '/static/images/flags/israel.png',
        image: '/static/images/news/yedioth.png',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.MEA_ARABNEWS_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.MIDDLEEAST,
        state: state.SAU,
        label: 'Arab News',
        cimage: '/static/images/flags/saudiarabia.png',
        image: '/static/images/news/arabnews.png',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.MEA_YOUM7_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.MIDDLEEAST,
        state: state.EGY,
        label: 'Youm7',
        cimage: '/static/images/flags/egypt.png',
        image: '/static/images/news/youm7.png',
        translation: { lang: 'Arabic', engine: 'Azure' },
        selected: true,
        cached: false
    },
    {
        value: source.MEA_HURRIYET_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.MIDDLEEAST,
        state: state.TUR,
        label: 'Hurriyet',
        cimage: '/static/images/flags/turkey.png',
        image: '/static/images/news/hurriyet.png',
        translation: { lang: 'Turkish', engine: 'Google' },
        selected: true,
        cached: false
    },
    {
        value: source.MEA_BBC_MIDDLEEAST_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.MIDDLEEAST,
        state: state.GBR,
        label: 'BBC Middle East',
        cimage: '/static/images/flags/uk.png',
        image: '/static/images/news/bbc.jpg',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.EA_JAPANTIMES_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.EASTASIA,
        state: state.JPN,
        label: 'Japan Times',
        cimage: '/static/images/flags/japan.png',
        image: '/static/images/news/japantimes.jpg',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.EA_ASAHISIMBUN_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.EASTASIA,
        state: state.JPN,
        label: 'Asahi Shimbun',
        cimage: '/static/images/flags/japan.png',
        image: '/static/images/news/asahishimbun.jpg',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.EA_KOREAHERALD_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.EASTASIA,
        state: state.KOR,
        label: 'Korea Herald',
        cimage: '/static/images/flags/skorea.png',
        image: '/static/images/news/koreaherald.jpg',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.EA_KOREATIMES_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.EASTASIA,
        state: state.KOR,
        label: 'Korea Times',
        cimage: '/static/images/flags/skorea.png',
        image: '/static/images/news/koreatimes.gif',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.EA_KCNA_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.EASTASIA,
        state: state.PRK,
        label: 'KCNA',
        cimage: '/static/images/flags/nkorea.png',
        image: '/static/images/news/kcna.jpg',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.EA_ASAHISIMBUN_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.EASTASIA,
        state: state.JPN,
        label: 'Asahi Shimbun',
        cimage: '/static/images/flags/japan.png',
        image: '/static/images/news/asahishimbun.jpg',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.EA_KOREAHERALD_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.EASTASIA,
        state: state.KOR,
        label: 'Korea Herald',
        cimage: '/static/images/flags/skorea.png',
        image: '/static/images/news/koreaherald.jpg',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.SEA_THESTAR_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.SOUTHEASTASIA,
        state: state.MYS,
        label: 'The Star Malaysia',
        cimage: '/static/images/flags/malaysia.png',
        image: '/static/images/news/thestar.jpg',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.SEA_JAKARTAPOST_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.SOUTHEASTASIA,
        state: state.IDN,
        label: 'Jakarta Post',
        cimage: '/static/images/flags/indonesia.png',
        image: '/static/images/news/jakarta.png',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.SEA_MANILATIMES_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.SOUTHEASTASIA,
        state: state.PHL,
        label: 'Manila Times',
        cimage: '/static/images/flags/philippines.png',
        image: '/static/images/news/manilatimes.jpg',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.SEA_THESTAR_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.SOUTHEASTASIA,
        state: state.MYS,
        label: 'The Star Malaysia',
        cimage: '/static/images/flags/malaysia.png',
        image: '/static/images/news/thestar.jpg',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.SEA_JAKARTAPOST_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.SOUTHEASTASIA,
        state: state.IDN,
        label: 'Jakarta Post',
        cimage: '/static/images/flags/indonesia.png',
        image: '/static/images/news/jakarta.png',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.SEA_MANILATIMES_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.SOUTHEASTASIA,
        state: state.PHL,
        label: 'Manila Times',
        cimage: '/static/images/flags/philippines.png',
        image: '/static/images/news/manilatimes.jpg',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.SA_DOWN_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.SOUTHASIA,
        state: state.PAK,
        label: 'Dawn',
        cimage: '/static/images/flags/pakistan.png',
        image: '/static/images/news/dawn.png',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.SA_DAILYTIMES_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.SOUTHASIA,
        state: state.PAK,
        label: 'Daily Times',
        cimage: '/static/images/flags/pakistan.png',
        image: '/static/images/news/dailytimes.png',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.SA_THEHINDU_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.SOUTHASIA,
        state: state.IND,
        label: 'The Hindu',
        cimage: '/static/images/flags/india.png',
        image: '/static/images/news/thehindu.png',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.SA_HINDUSTANTIMES_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.SOUTHASIA,
        state: state.IND,
        label: 'The Hindustan Times',
        cimage: '/static/images/flags/india.png',
        image: '/static/images/news/hindustantimes.png',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.SA_THEDAILYSTAR_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.SOUTHASIA,
        state: state.BGD,
        label: 'The Daily Star',
        cimage: '/static/images/flags/bangladesh.png',
        image: '/static/images/news/thedailystar.png',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.SA_DAILYFT_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.SOUTHASIA,
        state: state.LKA,
        label: 'Daily FT',
        cimage: '/static/images/flags/srilanka.png',
        image: '/static/images/news/dailyft.png',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.SA_PAKISTANTODAY_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.SOUTHASIA,
        state: state.PAK,
        label: 'Pakistan Today',
        cimage: '/static/images/flags/pakistan.png',
        image: '/static/images/news/pakistantoday.png',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.SA_DOWN_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.SOUTHASIA,
        state: state.PAK,
        label: 'Dawn',
        cimage: '/static/images/flags/pakistan.png',
        image: '/static/images/news/dawn.png',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.SA_THEHINDU_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.SOUTHASIA,
        state: state.IND,
        label: 'The Hindu',
        cimage: '/static/images/flags/india.png',
        image: '/static/images/news/thehindu.png',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.SA_HINDUSTANTIMES_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.SOUTHASIA,
        state: state.IND,
        label: 'The Hindustan Times',
        cimage: '/static/images/flags/india.png',
        image: '/static/images/news/hindustantimes.png',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.SA_THEDAILYSTAR_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.SOUTHASIA,
        state: state.BGD,
        label: 'The Daily Star',
        cimage: '/static/images/flags/bangladesh.png',
        image: '/static/images/news/thedailystar.png',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.SA_DAILYFT_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.SOUTHASIA,
        state: state.LKA,
        label: 'Daily FT',
        cimage: '/static/images/flags/srilanka.png',
        image: '/static/images/news/dailyft.png',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.SA_BBC_INDIA_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.SOUTHASIA,
        state: state.GBR,
        label: 'BBC India',
        cimage: '/static/images/flags/uk.png',
        image: '/static/images/news/bbc.jpg',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.AF_SOWETAN_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.AFRICA,
        state: state.ZAF,
        label: 'The Sowetan',
        cimage: '/static/images/flags/southafrica.png',
        image: '/static/images/news/sowetanlive.jpg',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.AF_DAILYGRAPHIC_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.AFRICA,
        state: state.GHA,
        label: 'The Daily Graphic',
        cimage: '/static/images/flags/ghana.png',
        image: '/static/images/news/dailygraphic.gif',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.AF_THEPUNCH_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.AFRICA,
        state: state.NGA,
        label: 'The Punch',
        cimage: '/static/images/flags/nigeria.png',
        image: '/static/images/news/punchng.gif',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.AF_THESTANDARD_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.AFRICA,
        state: state.KEN,
        label: 'The Standard',
        cimage: '/static/images/flags/kenya.png',
        image: '/static/images/news/standardmedia.gif',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.AF_ETHIOREPORTER_OPINION,
        type: type.NEWS_TYPE_OPINION,
        category: category.AFRICA,
        state: state.ETH,
        label: 'Ethiopian Reporter',
        cimage: '/static/images/flags/ethiopia.png',
        image: '/static/images/news/ethiopianreporter.png',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.AF_CAPETIMES_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.AFRICA,
        state: state.ZAF,
        label: 'Cape Times',
        cimage: '/static/images/flags/southafrica.png',
        image: '/static/images/news/capetimes.png',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.AF_THEPUNCH_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.AFRICA,
        state: state.NGA,
        label: 'The Punch',
        cimage: '/static/images/flags/nigeria.png',
        image: '/static/images/news/punchng.gif',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.AF_THESTANDARD_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.AFRICA,
        state: state.KEN,
        label: 'The Standard',
        cimage: '/static/images/flags/kenya.png',
        image: '/static/images/news/standardmedia.gif',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.AF_BBC_AFRICA_BREAKING,
        type: type.NEWS_TYPE_BREAKING,
        category: category.AFRICA,
        state: state.GBR,
        label: 'BBC Africa',
        cimage: '/static/images/flags/uk.png',
        image: '/static/images/news/bbc.jpg',
        translation: null,
        selected: true,
        cached: false
    },
    {
        value: source.R_DC_NEWS,
        category: category.RDISCUSSION,
        label: 'News',
        cimage: '/static/images/reddit/news.png',
        image: '/static/images/reddit/news.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_DC_POLITICS,
        category: category.RDISCUSSION,
        label: 'Politics',
        cimage: '/static/images/reddit/politics.jpg',
        image: '/static/images/reddit/politics.jpg',
        selected: true,
        cached: false
    },
    {
        value: source.R_DC_TRUEREDDITS,
        category: category.RDISCUSSION,
        label: 'TrueReddit',
        cimage: '/static/images/reddit/truereddit.png',
        image: '/static/images/reddit/truereddit.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_DC_WORLDNEWS,
        category: category.RDISCUSSION,
        label: 'WorldNews',
        cimage: '/static/images/reddit/worldnews.png',
        image: '/static/images/reddit/worldnews.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_SC_FUTUROLOGY,
        category: category.RSCIENCE,
        label: 'Futurology',
        cimage: '/static/images/reddit/futurology.png',
        image: '/static/images/reddit/futurology.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_SC_GADGETS,
        category: category.RSCIENCE,
        label: 'Gadgets',
        cimage: '/static/images/reddit/gadgets.png',
        image: '/static/images/reddit/gadgets.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_SC_SCIENCE,
        category: category.RSCIENCE,
        label: 'Science',
        cimage: '/static/images/reddit/science.png',
        image: '/static/images/reddit/science.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_SC_SPACE,
        category: category.RSCIENCE,
        label: 'Space',
        cimage: '/static/images/reddit/space.png',
        image: '/static/images/reddit/space.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_SC_TECHNOLOGY,
        category: category.RSCIENCE,
        label: 'Technology',
        cimage: '/static/images/reddit/technology.png',
        image: '/static/images/reddit/technology.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_LN_ASKHISTORIANS,
        category: category.RLEARNING,
        label: 'AskHistorians',
        cimage: '/static/images/reddit/askhistorians.png',
        image: '/static/images/reddit/askhistorians.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_LN_ASKSCINECE,
        category: category.RLEARNING,
        label: 'AskScience',
        cimage: '/static/images/reddit/askscience.png',
        image: '/static/images/reddit/askscience.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_LN_BOOKS,
        category: category.RLEARNING,
        label: 'Books',
        cimage: '/static/images/reddit/books.png',
        image: '/static/images/reddit/books.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_LN_EXPLAINLIKEIMFIVE,
        category: category.RLEARNING,
        label: 'ExplainLikeImFive',
        cimage: '/static/images/reddit/explainlikeimfive.png',
        image: '/static/images/reddit/explainlikeimfive.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_LN_HISTORY,
        category: category.RLEARNING,
        label: 'History',
        cimage: '/static/images/reddit/history.png',
        image: '/static/images/reddit/history.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_LN_PERSONALFINANCE,
        category: category.RLEARNING,
        label: 'PersonalFinance',
        cimage: '/static/images/reddit/personalfinance.png',
        image: '/static/images/reddit/personalfinance.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_LN_SPACE,
        category: category.RLEARNING,
        label: 'Space',
        cimage: '/static/images/reddit/space.png',
        image: '/static/images/reddit/space.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_LN_YOUSHOULDKNOW,
        category: category.RLEARNING,
        label: 'YouShouldKnow',
        cimage: '/static/images/reddit/youshouldknow.png',
        image: '/static/images/reddit/youshouldknow.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_LS_GETMOTIVATED,
        category: category.RLIFESTYLE,
        label: 'GetMotivated',
        cimage: '/static/images/reddit/getmotivated.png',
        image: '/static/images/reddit/getmotivated.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_LS_LIFEPROTIPS,
        category: category.RLIFESTYLE,
        label: 'LifeProTips',
        cimage: '/static/images/reddit/lifeprotips.png',
        image: '/static/images/reddit/lifeprotips.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_LS_TODAYILEARNED,
        category: category.RLIFESTYLE,
        label: 'TodayILearned',
        cimage: '/static/images/reddit/todayilearned.png',
        image: '/static/images/reddit/todayilearned.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_LS_UPLIFTINGNEWS,
        category: category.RLIFESTYLE,
        label: 'UpliftingNews',
        cimage: '/static/images/reddit/upliftingnews.png',
        image: '/static/images/reddit/upliftingnews.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_HL_FITNESS,
        category: category.RHEALTH,
        label: 'Fitness',
        cimage: '/static/images/reddit/fitness.png',
        image: '/static/images/reddit/fitness.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_HL_HEALTH,
        category: category.RHEALTH,
        label: 'Health',
        cimage: '/static/images/reddit/health.png',
        image: '/static/images/reddit/health.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_HL_NUTRITION,
        category: category.RHEALTH,
        label: 'Nutrition',
        cimage: '/static/images/reddit/nutrition.png',
        image: '/static/images/reddit/nutrition.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_PL_BERLIN,
        category: category.RPLACES,
        label: 'Berlin',
        cimage: '/static/images/reddit/berlin.png',
        image: '/static/images/reddit/berlin.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_PL_CANADA,
        category: category.RPLACES,
        label: 'Canada',
        cimage: '/static/images/reddit/canada.png',
        image: '/static/images/reddit/canada.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_PL_CANADAPOLITICS,
        category: category.RPLACES,
        label: 'CanadaPolitics',
        cimage: '/static/images/reddit/canadapolitics.png',
        image: '/static/images/reddit/canadapolitics.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_PL_LONDON,
        category: category.RPLACES,
        label: 'London',
        cimage: '/static/images/reddit/london.png',
        image: '/static/images/reddit/london.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_PL_MELBOURNE,
        category: category.RPLACES,
        label: 'Melbourne',
        cimage: '/static/images/reddit/melbourne.png',
        image: '/static/images/reddit/melbourne.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_PL_NYC,
        category: category.RPLACES,
        label: 'NYC',
        cimage: '/static/images/reddit/nyc.png',
        image: '/static/images/reddit/nyc.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_PL_SANFRANCISCO,
        category: category.RPLACES,
        label: 'Sanfrancisco',
        cimage: '/static/images/reddit/sanfrancisco.png',
        image: '/static/images/reddit/sanfrancisco.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_PL_SYDNEY,
        category: category.RPLACES,
        label: 'Sydney',
        cimage: '/static/images/reddit/sydney.png',
        image: '/static/images/reddit/sydney.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_PL_TOKYO,
        category: category.RPLACES,
        label: 'Tokyo',
        cimage: '/static/images/reddit/tokyo.png',
        image: '/static/images/reddit/tokyo.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_PL_TORONTO,
        category: category.RPLACES,
        label: 'Toronto',
        cimage: '/static/images/reddit/toronto.png',
        image: '/static/images/reddit/toronto.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_SS_HFY,
        category: category.RSHORTSTORIES,
        label: 'HFY',
        cimage: '/static/images/reddit/hfy.png',
        image: '/static/images/reddit/hfy.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_SS_NOSLEEP,
        category: category.RSHORTSTORIES,
        label: 'NoSleep',
        cimage: '/static/images/reddit/nosleep.png',
        image: '/static/images/reddit/nosleep.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_SS_SHORTSCIFISTORIES,
        category: category.RSHORTSTORIES,
        label: 'ShortScifiStories',
        cimage: '/static/images/reddit/shortscifistories.png',
        image: '/static/images/reddit/shortscifistories.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_SS_SHORTSTORIES,
        category: category.RSHORTSTORIES,
        label: 'ShortStories',
        cimage: '/static/images/reddit/shortstories.png',
        image: '/static/images/reddit/shortstories.png',
        selected: true,
        cached: false
    },
    {
        value: source.R_SS_WRITINGPROMPTS,
        category: category.RSHORTSTORIES,
        label: 'WritingPrompts',
        cimage: '/static/images/reddit/writingprompts.png',
        image: '/static/images/reddit/writingprompts.png',
        selected: true,
        cached: false
    }
];
