import * as country from '../constants/state';

export const conf_countries = [
    { value: country.ARG, code2: "AR", code3: "ARG", name: "Argentina", flag: "/static/images/flags/argentina.png" },
    { value: country.AUS, code2: "AU", code3: "AUS", name: "Australia", flag: "/static/images/flags/australia.png" },
    { value: country.BGD, code2: "BD", code3: "BGD", name: "Bangladesh", flag: "/static/images/flags/bangladesh.png" },
    { value: country.BRA, code2: "BR", code3: "BRA", name: "Brazil", flag: "/static/images/flags/brazil.png" },
    { value: country.CAN, code2: "CA", code3: "CAN", name: "Canada", flag: "/static/images/flags/canada.png" },
    { value: country.CHN, code2: "CN", code3: "CHN", name: "China", flag: "/static/images/flags/china.png" },
    { value: country.CZE, code2: "CZ", code3: "CZE", name: "Czech Republic", flag: "/static/images/flags/czech.png" },
    { value: country.EGY, code2: "EG", code3: "EGY", name: "Egypt", flag: "/static/images/flags/egypt.png" },
    { value: country.ETH, code2: "ET", code3: "ETH", name: "Ethiopia", flag: "/static/images/flags/ethiopia.png" },
    { value: country.FRA, code2: "FR", code3: "FRA", name: "France", flag: "/static/images/flags/france.png" },
    { value: country.DEU, code2: "DE", code3: "DEU", name: "Germany", flag: "/static/images/flags/germany.png" },
    { value: country.GHA, code2: "GH", code3: "GHA", name: "Ghana", flag: "/static/images/flags/ghana.png" },
    { value: country.HKG, code2: "HK", code3: "HKG", name: "Hong Kong", flag: "/static/images/flags/hongkong.png" },
    { value: country.HUN, code2: "HU", code3: "HUN", name: "Hungary", flag: "/static/images/flags/hungary.png" },
    { value: country.IND, code2: "IN", code3: "IND", name: "India", flag: "/static/images/flags/india.png" },
    { value: country.IDN, code2: "ID", code3: "IDN", name: "Indonesia", flag: "/static/images/flags/indonesia.png" },
    { value: country.IRN, code2: "IR", code3: "IRN", name: "Iran", flag: "/static/images/flags/iran.png" },
    { value: country.ISR, code2: "IL", code3: "ISR", name: "Israel", flag: "/static/images/flags/israel.png" },
    { value: country.JPN, code2: "JP", code3: "JPN", name: "Japan", flag: "/static/images/flags/japan.png" },
    { value: country.KEN, code2: "KE", code3: "KEN", name: "Kenya", flag: "/static/images/flags/kenya.png" },
    { value: country.PRK, code2: "KP", code3: "PRK", name: "Korea, Democratic People's Republic of", flag: "/static/images/flags/nkorea.png" },
    { value: country.KOR, code2: "KR", code3: "KOR", name: "Korea, Republic of", flag: "/static/images/flags/skorea.png" },
    { value: country.MYS, code2: "MY", code3: "MYS", name: "Malaysia", flag: "/static/images/flags/malaysia.png" },
    { value: country.MEX, code2: "MX", code3: "MEX", name: "Mexico", flag: "/static/images/flags/mexico.png" },
    { value: country.NGA, code2: "NG", code3: "NGA", name: "Nigeria", flag: "/static/images/flags/nigeria.png" },
    { value: country.PAK, code2: "PK", code3: "PAK", name: "Pakistan", flag: "/static/images/flags/pakistan.png" },
    { value: country.PHL, code2: "PH", code3: "PHL", name: "Philippines", flag: "/static/images/flags/philippines.png" },
    { value: country.POL, code2: "PL", code3: "POL", name: "Poland", flag: "/static/images/flags/poland.png" },
    { value: country.RUS, code2: "RU", code3: "RUS", name: "Russian Federation", flag: "/static/images/flags/russia.png" },
    { value: country.SAU, code2: "SA", code3: "SAU", name: "Saudi Arabia", flag: "/static/images/flags/saudiarabia.png" },
    { value: country.SGP, code2: "SG", code3: "SGP", name: "Singapore", flag: "/static/images/flags/singapore.png" },
    { value: country.ZAF, code2: "ZA", code3: "ZAF", name: "South Africa", flag: "/static/images/flags/southafrica.png" },
    { value: country.ESP, code2: "ES", code3: "ESP", name: "Spain", flag: "/static/images/flags/spain.png" },
    { value: country.LKA, code2: "LK", code3: "LKA", name: "Sri Lanka", flag: "/static/images/flags/srilanka.png" },
    { value: country.SWE, code2: "SE", code3: "SWE", name: "Sweden", flag: "/static/images/flags/sweden.png" },
    { value: country.TWN, code2: "TW", code3: "TWN", name: "Taiwan", flag: "/static/images/flags/taiwan.png" },
    { value: country.THA, code2: "TH", code3: "THA", name: "Thailand", flag: "/static/images/flags/thailand.png" },
    { value: country.TUR, code2: "TR", code3: "TUR", name: "Turkey", flag: "/static/images/flags/turkey.png" },
    { value: country.ARE, code2: "AE", code3: "ARE", name: "United Arab Emirates", flag: "/static/images/flags/uae.png" },
    { value: country.GBR, code2: "UK", code3: "GBR", name: "United Kingdom", flag: "/static/images/flags/uk.png" },
    { value: country.USA, code2: "US", code3: "USA", name: "United States", flag: "/static/images/flags/usa.png" }
];